### ISSUE TITLE
tunctl with external configure device

### ISSUE THREAD

**Issue by meox** [msantos/tunctl#12]
I have configured manually a tun0 device with a specific destination:
```
ip tuntap add dev tun0 mode tun user `id -un`
ip link set dev tun0 up
ip addr add dev tun0 local 192.168.123.1 remote 192.168.123.2
```

And than using `tunctl` I wrote a simple function to use this device:
```erlang
tun_attach(DevName) ->
  Opts = [tun, no_pi, {active, false}],
  tuncer:create(DevName, Opts).
```

The problem with this approach is if the tuncer crash: the interface tun0 goes down.

So I have 2 questions:
1) Should I pass the `persist` flag to the create function?
2) Is there a way to create the tun device from this lib setting a destination address?

**Comment by msantos** [comment]
On Mon, Sep 13, 2021 at 06:54:20AM -0700, Gian Lorenzo Meocci wrote:
> I have configured manually a tun0 device with a specific destination:
> ```
> ip tuntap add dev tun0 mode tun user `id -un`
> ip link set dev tun0 up
> ip addr add dev tun0 local 192.168.123.1 remote 192.168.123.2
> ```
> 
> And than using `tunctl` I wrote a simple function to use this device:
> ```erlang
> tun_attach(DevName) ->
>   Opts = [tun, no_pi, {active, false}],
>   tuncer:create(DevName, Opts).
> ```
> 
> The problem with this approach is if the tuncer crash: the interface tun0 goes down.

Usually the tuntap device would be run under a supervisor and restarted
on crash.

> So I have 2 questions:
> 1) Should I pass the `persist` flag to the create function?

See persist/2:

    {ok, Ref} = tuncer:create(DevName, Opts),
    tuncer:persist(Ref, true).

> 2) Is there a way to create the tun device from this lib setting a destination address?

Is this the "remote 192.168.123.2" option in the ip addr command?

I've never actually tried that. I guess the program writes packets to
the tuntap device with the source address set to 192.168.123.2?

Should be simple to add, will take a look at how ip-address(8) sets the
remote.

**Comment by meox** [comment]
Manually you can do:

```
ip tuntap add dev tun0 mode tun user `id -un`
ip link set dev tun0 up
ip addr add dev tun0 local 192.168.123.1 remote 192.168.123.2
```

**Comment by colrack** [comment]
> Is this the "remote 192.168.123.2" option in the ip addr command? I've never actually tried that. I guess the program writes packets to the tuntap device with the source address set to 192.168.123.2? Should be simple to add, will take a look at how ip-address(8) sets the remote.

Yes the program writes packets to the tun device with src address 192.168.123.2 and dest 192.168.123.1 (usually pkts coming from a L4 tunnel)
Note that /32 route is added automatically after adding the addr
`192.168.123.2 dev tun0 proto kernel scope link src 192.168.123.1`
so packets with dest 192.168.123.2 will be routed via the tun device and delivered to userspace
