### ISSUE TITLE
rebar3 error when I try to compile

### ISSUE THREAD

**Issue by jbdamiano** [msantos/tunctl#20]
make all
===> Error evaluating configuration script at "rebar.config.script":
{error,{81,file,
        {error,{badmatch,{error,eexist}},
               [{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,450}]},
                {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,123}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,270}]},
                {erl_eval,expr,5,[{file,"erl_eval.erl"},{line,446}]},
                {erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,123}]},
                {lists,foldl,3,[{file,"lists.erl"},{line,1267}]},
                {erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685}]},
                {file,eval_stream2,6,[{file,"file.erl"},{line,1504}]}]}}}

===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [Makefile:9: compile] Error 1

rebar version is rebar 3.17.0

**Comment by jbdamiano** [comment]
If I remove the rebar.config.script I can build with success

**Comment by msantos** [comment]
Try doing:
```
rm ${TMPDIR-/tmp}/test_setns.c
```
Seems the procket rebar.config.script creates a temp test C file with a well known path which causes the error: `{error,eexist}`

To see what is going on, run rebar in debug mode:

```
DEBUG=1 rebar3 do clean, compile
```
