### ISSUE TITLE
using tun device not working

### ISSUE THREAD

**Issue by obi458** [msantos/tunctl#27]
'Im on linux.

**a)** 

0) Create tun on gen_server using:

{ok,Dev} = tuncer:create("tun1",[tun,no_pi,{active,true]),
ok = tuncer:up(Dev,"10.8.0.2")

this works :-)

1)  start gen_tcp server listen on 10.8.0.2 on port 8081
2) start gen_tcp client connect to 10.8.0.2:8081 with option {ip,{10,8,0,2}}

I  expect to get message {tuntap,Pid,Data} on gen_server from 0)

But nothing happens!

**b)** 

0) Create tun on gen_server using:

{ok,Dev} = tuncer:create("tun1",[tun,no_pi,{active,true]),
ok = tuncer:up(Dev,"10.8.0.2")

this works :-)

1)  start gen_tcp server listen on 10.8.0.2 on port 8081
2) send an syn packet using tuncer:send(Dev,Packet)

Packet have srcAddr and destAddr of 10.8.0.2, destPort = 8081, srcPort = 4711
Packet is ok, i see it on tshark -i tun1

I expect to see Syn,Ack in tshark but always get an TCP Retransmission instead

I'm wrong?

Any hints?

**Comment by msantos** [comment]
Case **a** uses `{active,false}`:  use [tuncer:recv/1,2](https://hexdocs.pm/tunctl/tuncer.html#recv/1)

For details on sending data, see:
* [examples](https://github.com/msantos/tunctl/tree/master/examples)
* [6in4 tunnel](https://github.com/msantos/sut/tree/master)

**Comment by obi458** [comment]
The solution:

using a fake address, for example 10.8.0.3 and route it 

ip route add 10.8.0.3/32 dev tun1

a) gen_tcp client connect to 10.8.0.3:8081

b) set Packet srcAddr to 10.8.0.3 and destAddr to localAddr(example 192.168.178.23)
